[package]
name = "bitsrun-lib"
description = "Login and logout library for 10.0.0.55 at BIT"
version = "0.1.0"
edition = "2024"
license = "MIT"
homepage = "https://github.com/so1ve/bitsrun-lib-rs"
documentation = "https://github.com/so1ve/bitsrun-lib-rs"
repository = "https://github.com/so1ve/bitsrun-lib-rs"
readme = "README.md"
keywords = ["bit", "bitsrun", "srun", "srun-client", "srun-login"]
categories = ["authentication"]
authors = ["Spencer Woo <spencer.woo@outlook.com>", "Ray <so1ve@outlook.com>"]

[dependencies]
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls", # in favor of native openssl
], default-features = false }
tokio = { version = "1", features = ["full"] }
url = "2.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
hmac = "0.12"
md-5 = "0.10"
base64 = "0.21"
sha1 = "0.10"
directories = "5.0"
tabled = { version = "0.14", features = ["color"] }
humansize = "2.1"
chrono-humanize = "0.2"
chrono = "0.4"
log = "0.4"
pretty_env_logger = "0.5"
enable-ansi-support = "0.2"

[profile.release]
strip = "symbols"
